version: 0.2         

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      # packer
      - sudo yum install -y yum-utils shadow-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install packer
      # golang
      - wget -q https://go.dev/dl/go1.24.2.linux-amd64.tar.gz
      - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.24.2.linux-amd64.tar.gz

  pre_build:
    commands:
      - echo "Creating whitelist file"
      - echo $WHITELIST > provisioning/whitelist.pkr.hcl
      - packer init provisioning/packer-amd64.pkr.hcl
  build:
    commands:
      - echo "building for branch/tag $CODEBUILD_WEBHOOK_HEAD_REF"
      - export PATH=/usr/local/go/bin:$PATH
      - go version
      - cd webapp
      - npm install
      - cd ..
      - make
      - make install-aws